// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// // the Developer karem saad (KaremSD) 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqJ7CTsgLEORUl1c5bZlzgrPqYtc7Ha8',
    appId: '1:860427516991:web:7c913f32d9a6abbcb20c8a',
    messagingSenderId: '860427516991',
    projectId: 'graduation-plans-to-do',
    authDomain: 'graduation-plans-to-do.firebaseapp.com',
    storageBucket: 'graduation-plans-to-do.appspot.com',
    measurementId: 'G-RDDD0NMB4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1k1rh_QT1kt5XCIfbUI3rSXf_wwu7ZA',
    appId: '1:860427516991:android:813b8f083a420d13b20c8a',
    messagingSenderId: '860427516991',
    projectId: 'graduation-plans-to-do',
    storageBucket: 'graduation-plans-to-do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXD1pzZG_54M5-8P2i2D-oxBWH6n2GSaQ',
    appId: '1:860427516991:ios:9cc6ec44d161b74ab20c8a',
    messagingSenderId: '860427516991',
    projectId: 'graduation-plans-to-do',
    storageBucket: 'graduation-plans-to-do.appspot.com',
    iosClientId: '860427516991-muc7sutcunh77ugil7t0g6c08oh77o6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXD1pzZG_54M5-8P2i2D-oxBWH6n2GSaQ',
    appId: '1:860427516991:ios:9cc6ec44d161b74ab20c8a',
    messagingSenderId: '860427516991',
    projectId: 'graduation-plans-to-do',
    storageBucket: 'graduation-plans-to-do.appspot.com',
    iosClientId: '860427516991-muc7sutcunh77ugil7t0g6c08oh77o6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );
}
